<?php
//http://local.magento:8080/hello/Page/index?email=vlv@aaxiscommerce.com
/** @var \Aaxis\HelloPage\Block\Index $block */
$customer = $block->getCustomer();
?>

<?php if(!empty($customer)) : ?>
    <h1>Yay <?= $customer->getFirstname(); ?> <?= $customer->getLastname(); ?>, my first controller in M2 works!</h1>
<?php else: ?>
    <h1>Yay Anoymous, my first controller in M2 works!</h1>
<?php endif;?>




